### ISSUE TITLE
Pass conversation history to OpenWebUI

### ISSUE THREAD

**Issue by TheRealPSV** [TheRealPSV/ha-openwebui-conversation#8]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/TheRealPSV/ha-openwebui-conversation/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently, each request sent to OpenWebUI only includes the current prompt/message, and does not include conversation history.

### Describe the solution you'd like

Get conversation history and pass it to OpenWebUI as the messages

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by TheRealPSV** [comment]
Closed with v1.1.0

**Comment by Giwayume** [comment]
This doesn't appear to be working. If I ask:

```
How many meters are in a kilometer?
```

It responds with a simple answer. Then I ask a follow up question relying on the context of the previous question?

```
How about centimeters?
```

It goes on a ramble about what a centimeter is and its history, ignoring the fact that I'm implicitly asking "how many centimeters are in a kilometer?"

This line of contextual questioning works inside of OpenWebUI but not through this plugin.

**Comment by Giwayume** [comment]
Your plugin

<img width="686" height="553" alt="Image" src="https://github.com/user-attachments/assets/8904cd64-cfb2-41e0-8032-d3606b14e466" />

Ollama plugin

<img width="621" height="430" alt="Image" src="https://github.com/user-attachments/assets/fb956d6d-3fab-4a50-8286-89cc28b9ed39" />

**Comment by TheRealPSV** [comment]
@Giwayume can you create a separate issue for this, so it's easier for me to keep track of?
